name: Run GitHub Copilot Agent

on:
  push:
    branches:
      - feature/updated-clio-integrations
  pull_request:
    branches:
      - feature/updated-clio-integrations

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: github/copilot-agent@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
